name = "NormalizedRadonCDT"
uuid = "e0adff08-4a93-453d-8602-c3ed7d587dfa"
authors = ["Beckmann, Matthias <matthias.beckmann@uni-bremen.de>", "Beinert, Robert <robert.beinert@tu-berlin.de>", "Bresch, Jonas Jens Erhard Walter <bresch@tu-berlin.de>"]
version = "0.1.0"

[deps]
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Luxor = "ae8d54c2-7ccd-5906-9d76-62fc9837b5bc"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
