name = "NormalizedRadonCDT"
uuid = "e0adff08-4a93-453d-8602-c3ed7d587dfa"
authors = ["Beckmann, Matthias <matthias.beckmann@uni-bremen.de>",
           "Beinert, Robert <robert.beinert@tu-berlin.de>",
           "Bresch, Jonas Jens Erhard Walter <bresch@tu-berlin.de>"]
version = "0.1.0"
